- name: NVIM | Install nvim
  block:
    - name: NVIM | Remove existing Lazy.nvim plugin directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/nvim/lazy"
        state: absent
      changed_when: false

    - name: NVIM | Install nvim
      homebrew:
        name: nvim
        state: present
        update_homebrew: yes
