---
- name: Run NEOVIM
  ansible.builtin.import_tasks: tasks/darwin.yaml
  when: ansible_system == 'Darwin'

- name: Run NEOVIM
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_system == 'Linux' and ansible_distribution == 'Ubuntu'
