---
- name: TMUX | Run tmux task
  ansible.builtin.import_tasks: darwin.yaml
  when: ansible_system == 'Darwin'

- name: TMUX | Run tmux task
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_system == 'Linux' and ansible_distribution == 'Ubuntu'
