- name: Disable auto rearrangement of Spaces
  ansible.builtin.command: defaults write com.apple.dock workspaces-auto-swoosh -bool NO

- name: Restart the Dock
  ansible.builtin.command: killall Dock
