---
- name: Add the MobAI Homebrew tap
  community.general.homebrew_tap:
    name: mobai-app/tap
    state: present

- name: Install SimSlim
  community.general.homebrew:
    name: simslim
    state: present
