---
- name: Run LAZYGIT task
  ansible.builtin.import_tasks: darwin.yaml

- name: Run LAZYGIT
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_system == 'Linux' and ansible_distribution == 'Ubuntu'
