- name: SOPS | Download and install
  block:
    - name: Download SOPS binary
      ansible.builtin.get_url:
        url: https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.darwin
        dest: /tmp/sops-v3.9.0.darwin
        mode: "0755"

    - name: Move SOPS binary to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/sops-v3.9.0.darwin
        dest: /usr/local/bin/sops
        mode: "0755"
        remote_src: yes

    - name: Clean up temporary file
      ansible.builtin.file:
        path: /tmp/sops-v3.9.0.darwin
        state: absent

  become: true
