- name: Uninstall my dev setup
  hosts: localhost
  tasks:
    - name: Uninstall zsh
      homebrew:
        name: zsh
        state: absent

    - name: Uninstall stow
      homebrew:
        name: stow
        state: absent

    - name: Uninstall exa
      homebrew:
        name: exa
        state: absent

    - name: Uninstall nvim
      homebrew:
        name: nvim
        state: absent

    - name: Uninstall lazydocker
      homebrew:
        name: lazydocker
        state: absent

    - name: Uninstall lazygit
      homebrew:
        name: lazygit
        state: absent

    - name: Uninstall ripgrep
      homebrew:
        name: ripgrep
        state: absent

    - name: Uninstall tmux
      homebrew:
        name: tmux
        state: absent

    - name: Uninstall node
      homebrew:
        name: node
        state: absent

    - name: Uninstall skhd
      homebrew:
        name: skhd
        state: absent

    - name: Uninstall yabai
      homebrew:
        name: yabai
        state: absent

    - name: Uninstall fzf
      homebrew:
        name: fzf
        state: absent

    - name: Remove cloned dotfiles
      file:
        path: ~/.dotfiles
        state: absent
