---
- name: Create Arc User Data directory
  ansible.builtin.file:
    path: "{{ user_home }}/Library/Application Support/Arc/User Data/Default"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: '0755'
  tags: ['arc-devtools-shortcuts', 'arc-shortcuts']

- name: Configure Arc DevTools shortcuts
  ansible.builtin.template:
    src: devtools_shortcuts.json.j2
    dest: "{{ user_home }}/Library/Application Support/Arc/User Data/Default/devtools_shortcuts.json"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: '0644'
    backup: yes
  tags: ['arc-devtools-shortcuts', 'arc-shortcuts']

- name: Verify Arc DevTools shortcuts configuration
  ansible.builtin.debug:
    msg: "Arc DevTools shortcuts configured successfully. File created at: {{ devtools_shortcuts_file }}"
  tags: ['arc-devtools-shortcuts', 'arc-shortcuts']

- name: Remove Arc DevTools shortcuts (for testing/cleanup)
  ansible.builtin.file:
    path: "{{ devtools_shortcuts_file }}"
    state: absent
  tags: ['arc-devtools-shortcuts-cleanup', 'never']