- name: ZSH | Install zsh
  become: yes
  ansible.builtin.shell: sudo apt install zsh

- name: ZSH | Install oh-my-zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: yes
