- name: ZSH | Install zsh
  become: yes
  ansible.builtin.apt:
    name: zsh
    allow_change_held_packages: true

- name: ZSH | Install oh-my-zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
