---
- name: Run Hunk task
  ansible.builtin.import_tasks: darwin.yaml
  when: ansible_system == 'Darwin'

- name: Run Hunk Ubuntu task
  ansible.builtin.import_tasks: ubuntu.yaml
  when: ansible_system == 'Linux'
