---
- name: Install github cli
  homebrew:
    name: gh
    state: present
    update_homebrew: yes

- name: Install git-delta
  homebrew:
    name: git-delta
    state: present
    update_homebrew: yes

- name: Install diffnav
  homebrew:
    name: dlvhdr/formulae/diffnav
    state: present
    update_homebrew: yes

- name: List installed github cli extensions
  ansible.builtin.command: gh extension list
  register: gh_extensions
  changed_when: false

- name: Install github copilot extension
  ansible.builtin.command: gh extension install github/gh-copilot
  when: "'gh-copilot' not in gh_extensions.stdout"

- name: Install gh-dash extension
  ansible.builtin.command: gh extension install dlvhdr/gh-dash
  when: "'gh-dash' not in gh_extensions.stdout"
