---
- name: Install node
  homebrew:
    name: node
    state: present
    update_homebrew: yes

- name: Install nodemon globally
  npm:
    name: nodemon
    global: yes
    state: present

- name: Install pi-coding-agent globally
  npm:
    name: "@mariozechner/pi-coding-agent"
    global: yes
    state: present
