---
- name: Run node task
  ansible.builtin.import_tasks: tasks/darwin.yaml
  when: ansible_system == 'Darwin'

- name: Run node task
  ansible.builtin.import_tasks: tasks/darwin.yaml
  when: ansible_system == 'Linux' and ansible_distribution == 'Ubuntu'
