---
- name: Delete zsh file
  ansible.builtin.shell: rm -rf ~/.zshrc

- name: Run Stow task
  ansible.builtin.import_tasks: tasks/darwin.yaml
  when: ansible_system == 'Darwin'

- name: Run Stow task
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_system == 'Linux' and ansible_distribution == 'Ubuntu'
